### ISSUE TITLE
[V2] New Page: Meetup Page

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala/website-v2#119]
A Page with all the details + pics of our ongoing Bangalore meetup. 

cc @paperpsych @keraliss

**Comment by setusaurabh** [comment]
imo quote like the description i shared for Bitcoin Reading Club #109, this page should have these info:

- current/upcoming meet + how to subscribe/follow/RSVP that
- previous meet that we have had + proof of meet up for e.g. pictures/link to meetup etc for then to see how it was

**Comment by paperpsych** [comment]
@rajarshimaitra @setusaurabh First iteration, let me know if any section needs to be added or any changes. Give feedback on the layout please... the pictures, copy and all is up for change later. But if you like some copy and want to keep it, do comment on that too...


![Image](https://github.com/Bitshala/website-v2/assets/149538435/cffef8aa-ed24-4f13-9627-8d30bd17c43f)

**Comment by paperpsych** [comment]
Have moved this issue to "design review" please move it back to my WIP once you're done reviewing, thank you !!

**Comment by setusaurabh** [comment]
As discussed on call, sharing the following feedback - 
1. Explore upcoming meetups in banner CTA looks tap-able and we should find a way to avoid the tap or make that tap count
2. Upcoming meetup is nice - it should have some details like Name, Description, RSVP/ Wish to join in - taking users to meetup page
3. Similar to upcoming meetup, we can have a section just beneath it for previous meetups - which could have the similar card so that once an upcoming meetup becomes previous meetup, the same content could be used on the client side to show it there. All these cards' CTA will take users to meetup page. CTA in these meetups would be `Read more` / `Tell me more`. 

Rest to me looks awesome!
We can use some of these design inspirations for our reading club pages, as noted down the in the comment there.

**Comment by paperpsych** [comment]
Hello, the meetup page is done. Let me know if there's any changes needed.

![Image](https://github.com/Bitshala/website-v2/assets/149538435/4d8c42a6-0bfc-491c-b760-d2f78afb3889)

It's 90% the same as before.

Answering @setusaurabh 's concerns:

1. The CTA for upcoming meetups is clickable, it'll take the person to meetup or luma. My choice is luma because meetup has all our online events listed too which might cause an overload. Luma, will show just the BITDEVS and also be able to collect important info we need.

2. We are not including any of these details here because clicking on "tell me more" will take them to the registration page where all the details are and where they can RSVP.

3. I have added a carousel section with previous meetups. And again "tell me more" here too will take people to the specific meetup link of that event.

Rest lgtm. Let me know if any changes are needed. Thank you !!

**Comment by setusaurabh** [comment]
This looks good to me. Small change. 
1. "Previous Meetups" section will be called "Previous Meetups" 
2. Description of section can be modified later, but whenever we get chatgpt to suggest copywriting improvements, lets use the existing copy on the website as reference, else it comes out with its chatgpt way of writing which is distinct from our copy on website.
3. The scroll for previous meetups will start from left. 

There could be another design for when we dont have an upcoming meetup. Its possible that sometimes we may not have the next event card ready. Might be handy in that case. For e.g in "Upcoming Meetup", we can use the same banner but make it generic
- Banner with generic smudged description, smudged location and dates
- Description with generic smudged headline and text
- CTA can be "Coming soon on Meetup"

**Comment by paperpsych** [comment]
Okay, got it. Please write up some copy in the meantime, I'll need time to other stuff so copy might not be possible atm.

For when we don't have a upcoming meetup, I'll put a small card that says we don't have a meetup in [month], come back soon to check any updates.

I'm okay with meetup being the primary channel but having two CTAs that have the same function is not good UX. Only reason I like luma is we get to know more about the attendees, but we can build some mechanism to collect that info at the events itself so meetup for exposure and reach is fine!

Other changes that you suggested, I'll make them and upload the page here !!

**Comment by setusaurabh** [comment]
Sure, here's a copy suggestion for when we don't have an upcoming Meetup. 

```Meetup Coming Soon!

Sorry we don't have dates for our next upcoming Meetup. But we promise to share it soon! ```

Besides CTA should either take them to Meetup or Discord. Lets keep only one.
